name: hivehook
description: A powerful plugin system for Hive that adds hooks, lifecycle management, and middleware capabilities with built-in TTL, LRU caching, validation, and custom transformations.
version: 1.0.0-rc.0
homepage: https://github.com/Pathverse/hivehook/tree/hihook-integration
repository: https://github.com/Pathverse/hivehook/tree/hihook-integration

environment:
  sdk: ^3.9.0

dependencies:
  hive_ce: ^2.19.1
  hihook: ^0.1.0


dev_dependencies:
  test: ^1.28.0
  path: ^1.9.1
