name: hivehook
description: A powerful plugin system for Hive that adds hooks, lifecycle management, and middleware capabilities with built-in TTL, LRU caching, validation, and custom transformations.
version: 0.1.7
homepage: https://github.com/Pathverse/hivehook
repository: https://github.com/Pathverse/hivehook

environment:
  sdk: ^3.9.0

dependencies:
  hive_ce: ^2.17.0


dev_dependencies:
  test: ^1.28.0
